alias grep='grep --colour=auto'
alias ls='ls -FCG'
alias l='ls'
alias ll='ls -lh'
alias la='ls -A'
alias s='ls'
alias a='cd ..'
alias c='cd'
alias v='vim .'
alias vo='vim -o '
alias va='vo *'
alias ir='irb --noprompt --readline -r irb/completion'
alias irb='irb --readline -r irb/completion'
alias acroread='acroread -openInNewWindow'
alias date_for_filename='date +%Y-%m-%d_%H-%M-%S'
